### ISSUE TITLE
Build.tt的cs代码丢失

### ISSUE THREAD

**Issue by nishuihanlong** [NewLifeX/CubeDemo#1]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS2001	未能找到源文件“E:\Projects\CubeDemo\NewLife.School\Build.cs”。	NewLife.School	E:\Projects\CubeDemo\NewLife.School\CSC	1	活动的

**Comment by nnhy** [comment]
这个项目，已经合并到 NewLife.Cube 内部
